queue_rules:
  - name: default
    conditions:
      - check-success=Bitrise

pull_request_rules:
  - name: Resolve conflict
    conditions:
      - conflict
    actions:
        comment:
          message: This pull request has conflicts when rebasing. Can you please fix it @{{author}}? ðŸ™
  - name: Needs landing - Rebase
    conditions:
      - label=Needs Landing
      - "#approved-reviews-by>=1"
      - -draft
      - label!=Work In Progress
      - label!=Do Not Land
    actions:
      queue:
        method: rebase
        name: default
  - name: Needs landing - Squash
    conditions:
      - label=Needs Landing (Squash)
      - "#approved-reviews-by>=1"
      - -draft
      - label!=work in progress
      - label!=do not land
    actions:
      queue:
        method: squash
        name: default
  - name: String Import - Auto Approve
    conditions:
      - author=github-actions[bot]
      - title~=string-import*
      - or:
        - files~=^Blockzilla\/[^\/]*\/[^\/]*.lproj\/*
        - files~=^Blockzilla\/[^\/]*.lproj\/*
    actions:
      review:
        type: APPROVE
        message: Automatically approving string import
  - name: String Import - Auto Merge
    conditions:
      - author=github-actions[bot]
      - title~=string-import*
      - or:
        - files~=^Blockzilla\/[^\/]*\/[^\/]*.lproj\/*
        - files~=^Blockzilla\/[^\/]*.lproj\/*
    actions:
      queue:
        method: rebase
        name: default
  
