# Definitions for jobs that run periodically.  For details on the format, see
# `taskcluster/taskgraph/cron/schema.py`.  For documentation, see
# `taskcluster/docs/cron.rst`.
---

jobs:
    - name: l10-screenshots
      job:
          type: decision-task
          target-tasks-method: l10n_screenshots
          treeherder-symbol: l10-screenshots
      when: []  # Manual trigger only
    - name: bitrise-performance-test
      job:
          type: decision-task
          target-tasks-method: bitrise_performance_test
          treeherder-symbol: bitrise-performance
      when:
        by-project:
          firefox-ios:
            - {hour: 22, minute: 0}
          default: []
    - name: firebase-performance-test
      job:
          type: decision-task
          target-tasks-method: firebase_performance_test
          treeherder-symbol: firebase-performance
      when: 
        by-project:
          firefox-ios:
            - {hour: 22, minute: 0}
          default: []
    - name: beta-releases
      job:
        type: decision-task
        target-tasks-method: beta_releases
        treeherder-symbol: beta_releases
      when:
        by-project:
          firefox-ios:
            - {weekday: 'Tuesday', hour: 23, minute: 0}
            - {weekday: 'Thursday', hour: 23, minute: 0}
            - {weekday: 'Sunday', hour: 23, minute: 0}
          default: []

