---
autopush-feature:
  description: This property defines the autopush feature configuration
  hasExposure: true
  exposureDescription: ""
  variables:
    use-new-autopush-client:
      type: boolean
      description: "If true, the autopush client based on the Rust component will be used"
contextual-hint-feature:
  description: This set holds all features pertaining to contextual hints.
  hasExposure: true
  exposureDescription: ""
  variables:
    features-enabled:
      type: json
      description: "This property provides a lookup table of whether specific contextual hints are enabled.\n"
credit-card-autofill:
  description: This property defines the credit card autofill feature
  hasExposure: true
  exposureDescription: ""
  variables:
    credit-card-autofill-status:
      type: boolean
      description: "If true, we will allow user to use the credit autofill feature"
etp-coordinator-refactor:
  description: "This feature is for managing the roll out of the ETP coordinator code as part of the changes on the navigation in the app\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    enabled:
      type: boolean
      description: "Enables the feature\n"
general-app-features:
  description: The feature that contains feature flags for the entire application
  hasExposure: true
  exposureDescription: ""
  variables:
    pull-to-refresh:
      type: json
      description: This property defines whether or not the feature is enabled
    report-site-issue:
      type: json
      description: This property defines whether or not the feature is enabled
homescreenFeature:
  description: The homescreen that the user goes to when they press home or new tab.
  hasExposure: true
  exposureDescription: ""
  variables:
    pocket-sponsored-stories:
      type: boolean
      description: "This property defines whether pocket sponsored stories appear on the homepage.\n"
    sections-enabled:
      type: json
      description: "This property provides a lookup table of whether or not the given section should be enabled. If the section is enabled, it should be toggleable in the settings screen, and on by default.\n"
library-coordinator-refactor:
  description: "This feature is for managing the roll out of the library coordinator code as part of the changes on the navigation in the app\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    enabled:
      type: boolean
      description: "Enables the feature\n"
messaging:
  description: "The in-app messaging system\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    actions:
      type: json
      description: A growable map of action URLs.
    message-under-experiment:
      type: string
      description: "Deprecated. Please use \"experiment\": \"{experiment}\" instead."
    messages:
      type: json
      description: "A growable collection of messages, where the Key is the message identifier and the value is its associated MessageData.\n"
    on-control:
      type: string
      description: What should be displayed when a control message is selected.
      enum:
        - show-next-message
        - show-none
    styles:
      type: json
      description: "A map of styles to configure message appearance.\n"
    triggers:
      type: json
      description: "A collection of out the box trigger expressions. Each entry maps to a valid JEXL expression.\n"
onboarding-feature:
  description: The feature that controls whether to show or not Upgrade onboarding
  hasExposure: true
  exposureDescription: ""
  variables:
    first-run-flow:
      type: boolean
      description: "If true, we show the new Onboarding screen when the user for v106 version.\n"
    upgrade-flow:
      type: boolean
      description: "If true, we show the Upgrade onboarding screen when the user upgrades the version.\n"
onboarding-framework-feature:
  description: "The new onboarding framework feature that will allow onboarding to be experimentable through initial experiments.\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    cards:
      type: json
      description: "The list of available cards for onboarding.\n"
    conditions:
      type: json
      description: "A collection of out the box conditional expressions to be used in determining whether a card should show or not. Each entry maps to a valid JEXL expression.\n"
    dismissable:
      type: boolean
      description: "Whether or not the entire onboarding is dismissable by pressing an X at the top right corner of the screen.\n"
redux-integration-feature:
  description: "This feature is for managing the roll out of the Redux integration feature\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    enabled:
      type: boolean
      description: "Enables the feature\n"
search:
  description: "Configuring the functionality to do with search. This will be separated into smaller sub-features in later releases.\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    awesome-bar:
      type: json
      description: Configuring the awesome bar.
search-term-groups-feature:
  description: The feature that controls whether or not search term groups are enabled.
  hasExposure: true
  exposureDescription: ""
  variables:
    grouping-enabled:
      type: json
      description: This property provides a lookup table of whether or not the given grouping should be enabled.
settings-coordinator-refactor:
  description: "This feature is for managing the roll out of the settings coordinator code as part of the changes on the navigation in the app\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    enabled:
      type: boolean
      description: "Enables the feature\n"
share-extension-coordinator-refactor:
  description: "This feature is for managing the roll out of the share extension coordinator as part of the changes to the navigation in the app\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    enabled:
      type: boolean
      description: "Enables the feature\n"
share-sheet:
  description: This feature define the redesign of the share sheet
  hasExposure: true
  exposureDescription: ""
  variables:
    move-actions:
      type: boolean
      description: If true copy and send to device are moved to share sheet
    toolbar-changes:
      type: boolean
      description: If true share option is shown on the toolbar
shopping2023:
  description: "The configuration setting for the status of the Fakespot feature\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    config:
      type: json
      description: "A Map of website configurations\n"
    status:
      type: boolean
      description: "Whether the Fakespot feature is enabled or disabled\n"
spotlight-search:
  description: Add pages as items findable with Spotlight.
  hasExposure: true
  exposureDescription: ""
  variables:
    enabled:
      type: boolean
      description: "If this is true, then on each page load adds a new item to Spotlight."
    icon-type:
      type: string
      description: "The icon that is displayed next to the item in the search results. If this is `null`, then no icon is displayed.\n"
    keep-for-days:
      type: int
      description: "Number of days to keep the item before automatic deletion. If this is left `null`, then it is left to iOS's default.\n"
    searchable-content:
      type: string
      description: "The text content that is made searchable. If this is `null` then no additional content is used, and only the title and URL will be used.\n"
start-at-home-feature:
  description: The controls for Start at Home feature
  hasExposure: true
  exposureDescription: ""
  variables:
    setting:
      type: string
      description: This property provides a default setting for the startAtHomeFeature
      enum:
        - after-four-hours
        - always
        - disabled
tabTrayFeature:
  description: The tab tray screen that the user goes to when they open the tab tray.
  hasExposure: true
  exposureDescription: ""
  variables:
    sections-enabled:
      type: json
      description: "This property provides a lookup table of whether or not the given section should be enabled. If the section is enabled, it should be toggleable in the settings screen, and on by default."
wallpaper-feature:
  description: This property defines the configuration for the wallpaper feature
  hasExposure: true
  exposureDescription: ""
  variables:
    configuration:
      type: json
      description: This property defines the configuration for the wallpaper feature
    onboarding-sheet:
      type: boolean
      description: This property defines whether the wallpaper onboarding is shown or not
zoom-feature:
  description: "The configuration for the status of the zoom feature\n"
  hasExposure: true
  exposureDescription: ""
  variables:
    status:
      type: boolean
      description: "Whether the page zoom feature is enabled or not\n"
