queue_rules:
  - name: rebase-queue
    queue_conditions:
      - check-success=Bitrise
    merge_method: rebase
  - name: squash-queue
    queue_conditions:
      - check-success=Bitrise
    merge_method: squash

pull_request_rules:
  - name: Resolve conflict
    conditions:
      - conflict
    actions:
      comment:
        message: This pull request has conflicts when rebasing. Could you fix it @{{author}}? 🙏
  - name: Bitrise update - Auto Merge
    conditions:
      - author=github-actions[bot]
      - check-success=Bitrise
      - files=bitrise.yml
      - -files~=^(?!bitrise.yml).+$
      - head=update-br-new-xcode-version
    actions:
      review:
        type: APPROVE
        message: Github-action[bot] 💪
      queue:
        name: rebase-queue
  - name: Rust Component Upgrade - Auto Merge
    conditions:
      - author=github-actions[bot]
      - check-success=Bitrise
      - files=Client.xcodeproj/project.pbxproj
      - files=Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
    actions:
      review:
        type: APPROVE
        message: Github-action[bot] 💪
      queue:
        name: rebase-queue
  - name: L10N - Auto Merge
    conditions:
      - author=github-actions[bot]
      - check-success=Bitrise
      - files~=^.+\.strings$
      - -files~=^(?!^.+\.strings).+$
    actions:
      review:
        type: APPROVE
        message: LGTM 😎
      queue:
        name: rebase-queue
  - name: Needs landing - Rebase
    conditions:
      - check-success=Bitrise
      - label=Needs Landing
      - "#approved-reviews-by>=1"
      - -draft
      - label!=Do Not Merge ⛔️
    actions:
      queue:
        name: rebase-queue
  - name: Needs landing - Squash
    conditions:
      - check-success=Bitrise
      - label=Needs Landing (Squash)
      - "#approved-reviews-by>=1"
      - -draft
      - label!=Do Not Merge ⛔️
    actions:
      queue:
        name: squash-queue
priority_rules:
  - name: priority for queue `rebase-queue`
    conditions:
      - queue-name=rebase-queue
    priority: 2250
