disabled_rules: # rule identifiers to exclude from running
  - variable_name
  - todo
  - trailing_newline
  - type_name
  - function_body_length
  - missing_docs
  - valid_docs
  - cyclomatic_complexity
  - type_body_length
  - function_parameter_count
  - file_length
  - mark
  - unused_closure_parameter
  - empty_parentheses_with_trailing_closure
  - redundant_string_enum_value
  - large_tuple
  - class_delegate_protocol
  - syntactic_sugar
  - implicit_getter
  - weak_delegate
  - shorthand_operator
  - trailing_comma
  - unused_optional_binding
  - private_over_fileprivate
  - empty_enum_arguments
  - discarded_notification_center_observer
  - block_based_kvo
  - nesting
  - is_disjoint
  - multiple_closures_with_trailing_closure
  - fallthrough
  - switch_case_alignment
  - trailing_whitespace
  - leading_whitespace
  - operator_whitespace
  - legacy_cggeometry_functions
  - unneeded_break_in_switch
  - closure_parameter_position
opt_in_rules: # some rules are only opt-in
  - closing_brace
  - opening_brace
  - return_arrow_whitespace
  - trailing_semicolon
  - statement_position
  - explicit_init
  - shorthand_operator
  - file_header
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  - ThirdParty
  - FxA
  - FxAClient
  - build
  - UITests/EarlGrey.swift
  - Storage/ThirdParty/SwiftData.swift
  - UITests/
  - XCUITests/
  - SyncTests/
  - StorageTests/
  - ReadingListTests/
  - ClientTests/
  - AccountTests/
  - fastlane/
  - SharedTests/
  - Client/Assets/Search/get_supported_locales.swift

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
trailing_semicolon: error
empty_count: error
closing_brace: error
opening_brace: error
return_arrow_whitespace: error
statement_position: error
colon: error
comma: error
force_try: warning
force_cast: warning


file_header:
  required_string: "/* This Source Code Form is subject to the terms of the Mozilla Public\n * License, v. 2.0. If a copy of the MPL was not distributed with this\n * file, You can obtain one at http://mozilla.org/MPL/2.0/. */"
line_length: 1000

reporter: "json" # reporter type (xcode, json, csv, checkstyle)
