/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

import Foundation
import XCTest

class StringExtensionsTests: XCTestCase {
    func testContains() {
        XCTAssertTrue("abcde".contains("abcde"))
        XCTAssertTrue("abcde".contains(""))
        XCTAssertTrue("abcde".contains("a"))
        XCTAssertTrue("abcde".contains("e"))
        XCTAssertFalse("abcde".contains("f"))
        XCTAssertFalse("abcde".contains("fa"))
        XCTAssertFalse("abcde".contains("ef"))
    }

    func testStartsWith() {
        XCTAssertTrue("abcde".startsWith("abcde"))
        XCTAssertTrue("abcde".startsWith(""))
        XCTAssertTrue("abcde".startsWith("a"))
        XCTAssertTrue("abcdea".startsWith("a"))
        XCTAssertFalse("abcde".startsWith("fa"))
        XCTAssertFalse("abcde".startsWith("af"))
        XCTAssertFalse("abcde".startsWith("b"))
    }

    func testEndsWith() {
        XCTAssertTrue("abcde".endsWith("abcde"))
        XCTAssertTrue("abcde".endsWith(""))
        XCTAssertTrue("abcde".endsWith("e"))
        XCTAssertTrue("abcdea".endsWith("a"))
        XCTAssertFalse("abcde".endsWith("fe"))
        XCTAssertFalse("abcde".endsWith("ef"))
        XCTAssertFalse("abcde".endsWith("d"))
    }

    func testEllipsize() {
        XCTAssertEqual( "".ellipsize(0), "…")
        XCTAssertEqual("a".ellipsize(1), "…")
        XCTAssertEqual("ba".ellipsize(2), "…")
        XCTAssertEqual( "123456789".ellipsize(3), "1…9")
        XCTAssertEqual( "123456789".ellipsize(4), "12…9")
        XCTAssertEqual( "123456789".ellipsize(5), "12…89")
        XCTAssertEqual( "123456789".ellipsize(6), "123…89")
        XCTAssertEqual( "123456789".ellipsize(7), "123…789")
        XCTAssertEqual( "123456789".ellipsize(8), "1234…789")
        XCTAssertEqual( "123456789".ellipsize(9), "1234…6789")
        XCTAssertEqual( "123456789".ellipsize(10), "123456789")
        XCTAssertEqual( "https://www.google.com".ellipsize(22), "https://www…google.com")
        XCTAssertEqual( "https://www.google.com".ellipsize(10), "https….com")
        XCTAssertEqual("http://www.longurlmaker.com/go?id=KEMQORCWMKXIBPGFZNXDCRHZWYWYSCZDHMTVDWRQGPZIEFOESLHVDOVAMSYFUYIBKCWOYOEFDDNIIBMBNTXQISQVKPAFNJGYMDMLSQQWUEEDGRETLCKTUAOFQPKDZRBMVNXNEOKYSOBYGGRRIBLDCAJSQUWPLYBHMZVQNFPFUREAXWSGYEKAETTUNQKZOLHBLCRYIHECYIDWEWDDANEEHYZUOJUDVBEGEWEMDJPCRTZWQCAQPEVWCURQELTZNYGRULEXUUAMNZIDBIURNQOPLFGPRZPFXVXSGCQAWQMKQVOREIJRYXGJDMZVMOAKJXCQZTQWJDGZYURCDBUCYAMCNLXAZYKJWNZWGQSQTZQSUHUXIOZHPLKCXHDWGNGCBFYHWRYPQOHKVCIERIMGUWJREMOLAUNBAMJWDHMUWUFRWNWNWJUQGEIKRWVSRJUSVEOZMBTIVZZRMWFJFAZLFHWWESOVCJNXNCXZDRHYQHQDDWMJWLVBTSYXKNTNWHKJJIJNZQMPXDSBZELWQGXJYWHJJAWGIHQSPZFPPSEMVWOUBZQRGOAEKIOUJLARTQJJPPYFIDSDZGYBFPSLETQOBFJLRKCLBMVQBTWKWONWUMXABQMFJDULJDWAOZMPLHGNACXXQLULXSLYIYESBYEKCBLQAXFMEMAFOXDFJXQGQCFZAJSBIWMKYXAZUGLZSLEHJIMTFCZWFFVFONHWKUHIRIHMPTMHFRPOZBIFEHBKNWPBKXYURGDJOKWDEJLJABYZCGEHNFRBCHDMFCGWIJGXUDAYMMHMNFMQLQYZWPAYXELCGSZOCGLWJMVWYDIMJVDVLBVIRWHOASRGKQUMXGJGSEDRHMEQHHMTIHBADIPDBGJLXEXUKHBCLETTRXKYFWRNDTOGBDKCKTOIXMDHTFKFJDYBBJZGFRUJKJQLNAOXTCFRPJZIOJNYNMZPVYWAPQJZAALNAAKTDQLSAKAOTOMHALWVKSWAJGAJGMWHMHAPYMIYWJMQXZYYKUUVMQVWXWFEICLUJMKIYSGVBTMZSKXDFRYRIUNGQTLYVWTFJDNIWUEYNQXGBVJGMIYVCMBTFMRBJLGSPTBLNFKAWHHXCQEPZCKCPMVUZNVJYCBNVDZJIJKERRBUIGJHIUJYHESGSOPRRREMUEVDOFHFXJZFPJMYDVWKAPRTEHKVYPITTDWIJDOGNOLCXYBBUYMUNENSLYNJNWDHAZPJDDQQRCTPAVRUTDPHHDZSBNCPJGWJFMTJPKAHNUXNPOIIRYPZCPSECUTMAQVGCPPSAQZNKXAZLJICIXCKMUPPPIBPZXWBMMUMCUZNRAMCKUFTSHDFCTURCVGBSDDFPXRSRRFIRSKCNPVFXZKZSFQUAXVTBYYQWPJNHPVZHFBUVXATWLSPQJJRGFKHEIYAYINFXJEFOFAKDADZMVODFYULEETJNSJLAXQYGVDVBEFEFJDRFSUKQPWVUQEHINTJLKISFMNGQTKVCONIGISXYPSSFWAOKTYWDGOJSCQJWAFZPSHVBATZPMSUISITMGPQNEZGGPPCQUCFNJBOJVOYHGTQYCJKJZAWEACLPROGMQLZZNOIICHPIAFGCPRLPSITSKEICSOPJZOINCRVEYLNZQTCGLOWDWQVHVDKORZXRNFEQWAVVLIUCCXINLFQHVMPQPZEHYBYMHDCEDXZOGUQIRZVDEMLAYAQOZVVYXUKFXNJBLJPRDGZVGVYKHJLGKCUKXPIVJTAHGKIRTYJWEISKEQVMAGSKINUGCDCMWCTDMCVFAECENUPRLKDLRWVZJQGMTIZQLTTYVOEVTGAGBPXMABXRXTQHKXTDFSUQLNOHCSCVZDBASZNTBLKZFAGPXATDTNUFBIMDBPZBTBBMBPFCAPCFQIUOJORDBLICUVGWLFXEHZQIOWKOLMTCVOQFCIIETRHONNLZTIDAHUIWRTKCGEECTVHVDQAXIHLWUWVOFZONUXJLQUOWYSZRNGNRXNOGUACPXXDCWSPQPZCGTQDSICKWJXOGLCMGCPWAMACJSSAHSCOLSRDBTNYCLMJXOWDR".ellipsize(63), "http://www.longurlmaker.com/go?…PWAMACJSSAHSCOLSRDBTNYCLMJXOWDR")
    }

}
