use_frameworks!
  use_frameworks!	
 
 post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'YES'
      config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
    end
  end
end

target 'Leanplum-SDK_Example' do
  platform :ios, '8.0'

  pod 'Leanplum-iOS-SDK', :path => '../'
  
  target 'Leanplum-SDK_Tests' do
      inherit! :search_paths

      pod 'Leanplum-iOS-SDK', :path => '../'
      pod 'OCMock', '~> 3.3.1'
      pod 'OHHTTPStubs'
  end
end
