// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/

import Foundation

/// Defines the state for the address toolbar.
public struct AddressToolbarState {
    /// View state for the `Location View`  in the address toolbar
    let locationViewState: LocationViewState

    /// Navigation actions of the address toolbar
    let navigationActions: [ToolbarElement]

    /// Page actions of the address toolbar
    let pageActions: [ToolbarElement]

    /// Browser actions of the address toolbar
    let browserActions: [ToolbarElement]

    /// The position of the toolbar border to be displayed
    let borderPosition: AddressToolbarBorderPosition?

    /// Whether toolbar change should be displayed animated
    let shouldAnimate: Bool

    // We need this init as by default the init generated by the compiler for the struct will be internal and
    // can therefor not be used outside of the ToolbarKit
    public init(locationViewState: LocationViewState,
                navigationActions: [ToolbarElement],
                pageActions: [ToolbarElement],
                browserActions: [ToolbarElement],
<<<<<<< HEAD
                borderPosition: AddressToolbarBorderPosition?) {
        self.locationViewState = locationViewState
=======
                borderPosition: AddressToolbarBorderPosition?,
                shouldAnimate: Bool) {
        self.locationViewConfiguration = locationViewConfiguration
>>>>>>> 68cacdc07 (Bugfix FXIOS-9857 Normal tabs appear in private top tabs tray briefly during launch (#24667))
        self.navigationActions = navigationActions
        self.pageActions = pageActions
        self.browserActions = browserActions
        self.borderPosition = borderPosition
        self.shouldAnimate = shouldAnimate
    }
}
