#!/bin/bash

# Directory containing your custom hooks
HOOKS_DIR="hooks"

# Check if hooks have already been installed in the .git/hooks directory
# We check for one example hook to verify, you can change this to your preference
required_hooks=("prepare-commit-msg" "post-checkout")
missing_hooks=()

for hook in "${required_hooks[@]}"; do
  if [ ! -f ".git/hooks/$hook" ]; then
    missing_hooks+=("$hook")
  fi
done

if [ ${#missing_hooks[@]} -ne 0 ]; then
  echo "Missing hooks: ${missing_hooks[*]}. Running setup_hooks.sh to install them."
  # Run the setup script to copy the hooks
  ./setup_hooks.sh
else
  echo "Git hooks are already installed."
fi