#!/bin/sh

VERSION=$1

case $VERSION in
    ''|*[!0-9]*)
        echo "Usage: set-build-version numeric-build-version"
        exit 1
        ;;
    *)
        ;;
esac

if [ ! -d Client.xcodeproj ]; then
  echo "Please run this from the project root (where the .xcodeproj lives)"
  exit 1
fi

echo "Setting to $VERSION"

sed -i '' "s/MOZ_BUILD_ID = .*/MOZ_BUILD_ID = $VERSION/g" Client/Configuration/BaseConfig.xcconfig
