// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/

import Foundation

/// This struct defines all the image identifiers of icons and images used in the app.
/// When adding new identifiers, please respect alphabetical order.
/// Sing the song if you must.
public struct ImageIdentifiers {
    public struct Medium {
        public static let cross = "crossMedium"
    }

    public struct Large {
        public static let appendUp = "appendUpLarge"
        public static let appMenu = "appMenuLarge"
        public static let avatarCircle = "avatarCircleLarge"
        public static let back = "backLarge"
        public static let bookmark = "bookmarkLarge"
        public static let bookmarkFill = "bookmarkFillLarge"
        public static let bookmarkSlash = "bookmarkSlashLarge"
        public static let bookmarkTrayFill = "bookmarkTrayFillLarge"
        public static let checkmark = "checkmarkLarge"
        public static let chevronDown = "chevronDownLarge"
        public static let chevronLeft = "chevronLeftLarge"
        public static let chevronRight = "chevronRightLarge"
        public static let chevronUp = "chevronUpLarge"
        public static let creditCard = "creditCardLarge"
        public static let cross = "crossLarge"
        public static let delete = "deleteLarge"
        public static let deviceDesktop = "deviceDesktopLarge"
        public static let deviceDesktopSend = "deviceDesktopSendLarge"
        public static let deviceMobile = "deviceMobileLarge"
        public static let download = "downloadLarge"
        public static let edit = "editLarge"
        public static let folder = "folderLarge"
        public static let forward = "forwardLarge"
        public static let globe = "globeLarge"
        public static let helpCircle = "helpCircleLarge"
        public static let history = "historyLarge"
        public static let home = "homeLarge"
        public static let logoFirefox = "logoFirefoxLarge"
        public static let lightbulb = "lightbulbLarge"
        public static let link = "linkLarge"
        public static let login = "loginLarge"
        public static let plus = "plusLarge"
        public static let qrCode = "qrCodeLarge"
        public static let tabTray = "tabTrayLarge"
    }

    public static let addShortcut = "action_pin"
    public static let addToReadingList = "addToReadingList"
    public static let badgeMask = "badge-mask"
    public static let bottomSheetClose = "bottomSheet-close"
    public static let circleFill = "circle.fill"
    public static let closeLargeButton = "close-large"
    public static let creditCardPlaceholder = "credit_card_placeholder"
    public static let errorAutofill = "error_autofill"
    public static let emptySyncImageName = "emptySync"
    public static let findInPage = "menu-FindInPage"
    public static let firefoxFavicon = "faviconFox"
    public static let homeHeaderLogoBall = "fxHomeHeaderLogoBall"
    public static let homeHeaderLogoText = "fxHomeHeaderLogoText"
    public static let homepagePocket = "homepage-pocket"
    public static let largePrivateTabsMask = "largePrivateMask"
    public static let libraryPanelSearch = "search"
    public static let libraryReadingList = "library-readinglist"
    public static let lockBlocked = "lock_blocked"
    public static let lockVerifed = "lock_verified"
    public static let logo = "splash"
    public static let logoAmex = "logo_amex"
    public static let logoDiners = "logo_diners"
    public static let logoDiscover = "logo_discover"
    public static let logoJcb = "logo_jcb"
    public static let logoMastercard = "logo_mastercard"
    public static let logoMir = "logo_mir"
    public static let logoUnionpay = "logo_unionpay"
    public static let logoVisa = "logo_visa"
    public static let menuBadge = "menuBadge"
    public static let menuWarning = "menuWarning"
    public static let menuWarningMask = "warning-mask"
    public static let navTabCounter = "nav-tabcounter"
    public static let newPrivateTab = "quick_action_new_private_tab"
    public static let nightMode = "menu-NightMode"
    public static let onboardingWelcomev106 = "onboardingWelcome"
    public static let onboardingSyncv106 = "onboardingSync"
    public static let onboardingNotification = "onboardingNotification"
    public static let onboardingNotificationsCTD = "onboardingNotificationsCTD"
    public static let onboardingWelcomeCTD = "onboardingWelcomeCTD"
    public static let onboardingSyncCTD = "onboardingSyncCTD"
    public static let paste = "menu-Paste"
    public static let pasteAndGo = "menu-PasteAndGo"
    public static let pinSmall = "pin_small"
    public static let qrCodeScanBorder = "qrcode-scanBorder"
    public static let qrCodeScanLine = "qrcode-scanLine"
    public static let qrCodeLight = "qrcode-light"
    public static let qrCodeLightTurnedOn = "qrcode-isLighting"
    public static let privateMaskSmall = "smallPrivateMask"
    public static let privateModeBadge = "privateModeBadge"
    public static let readingList = "menu-panel-ReadingList"
    public static let removeFromShortcut = "action_unpin"
    public static let reportSiteIssue = "menu-reportSiteIssue"
    public static let settings = "menu-Settings"
    public static let share = "action_share"
    public static let signinSync = "signin-sync"
    public static let signinSyncQRButton = "qr-code-icon-white"
    public static let sponsoredStar = "sponsored-star"
    public static let subtract = "subtract"
    public static let sync = "menu-sync"
    public static let syncedDevicesIcon = "synced_devices"
    public static let upgradeBackground = "onboardingBackground"
    public static let upgradeCloseButton = "updateCloseButton"
    public static let warning = "menu-warning"
    public static let breachedWebsite = "Breached Website"
    public static let whatsNew = "whatsnew"
    public static let zoomIn = "menu-ZoomIn"
}
