#if !canImport(ObjectiveC)
import XCTest

extension AStarTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AStarTests = [
        ("testEmptyPath", testEmptyPath),
        ("testOptimalPath", testOptimalPath),
        ("testStraightPath", testStraightPath),
        ("testTwoSegmentPath", testTwoSegmentPath),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AStarTests.__allTests__AStarTests),
    ]
}
#endif
