excluded:
  - Tests
  - Carthage
  - Pods
  - Utils/**/.build
  - DependencyManagerTests
  - Sources/SentryCrash
  - vendor
whitelist_rules:
  #- attributes
  - class_delegate_protocol
  - closing_brace
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - colon
  - comma
  - compiler_protocol_init
  #- conditional_returns_on_newline
  - control_statement
  - custom_rules
  - cyclomatic_complexity
  - dynamic_inline
  - empty_count
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - explicit_init
  #- file_header
  - file_length
  - first_where
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  - function_parameter_count
  - generic_type_name
  - implicit_getter
  - large_tuple
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - line_length
  - mark
  #- missing_docs
  #- nesting
  - nimble_operator
  - number_separator
  - object_literal
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - overridden_super_call
  - private_outlet
  - private_unit_test
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
  - shorthand_operator
  - sorted_imports
  - statement_position
  - switch_case_on_newline
  - syntactic_sugar
  - todo
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  #- trailing_whitespace
  - type_body_length
  - type_name
  - unused_closure_parameter
  - unused_enumerated
  - unused_optional_binding
  - valid_ibinspectable
  - identifier_name
  - vertical_parameter_alignment
  - vertical_whitespace
  - void_return
  - weak_delegate
identifier_name:
  min_length:
    - 2
    - 1
force_try:
  severity: warning
force_unwrapping:
  severity: error
line_length:
  - 220
type_name:
  min_length:
    - 2
    - 1
