name: Execute test plan

on:
  workflow_call:
    inputs:
        test-plan:
            required: true
            type: string
        developer-dir:
            required: true
            type: string
    
jobs:

  execute_test_plan:
    runs-on: macos-13
    name: Test ${{ inputs.test-plan }} module if needed
    env:
      DEVELOPER_DIR: ${{ inputs.developer-dir }}

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare environment
        uses: ./.github/actions/prepare_environment
        with:
          core-token: ${{ secrets.IOS_CORE_TOKEN }}

      - name: Run ${{ inputs.test-plan }} tests
        env:
          SCAN_DERIVED_DATA_PATH: ${{ steps.get_derived_data_path.outputs.derived_data_path_from_file }}
        run: bundle exec fastlane run run_tests test_without_building:true testplan:"${{ inputs.test-plan }}"

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3.7.6
        with:
          report_paths: '**/test_output/xml/report.junit'
          github_token: ${{ secrets.GITHUB_TOKEN }}